apiVersion: v1
kind: Service
metadata:
  name: log-generator-service
  namespace: log-generator
  labels:
    app.kubernetes.io/name: log-generator
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: log-generator
    app.kubernetes.io/component: generator

---
apiVersion: v1
kind: Service
metadata:
  name: log-generator-headless
  namespace: log-generator
  labels:
    app.kubernetes.io/name: log-generator
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: log-generator
    app.kubernetes.io/component: generator
