# High Performance Configuration - Target: 5,000 logs/second (300,000 logs/minute)
generators:
  endpoint:
    enabled: true
    frequency: 120000  # 2,000 logs/second
    templates:
      - level: INFO
        messageTemplate: "HTTP {method} {path} - {status} {responseTime}ms - IP: {clientIP}"
        probability: 0.8
        metadata:
          component: api-gateway
      - level: ERROR
        messageTemplate: "HTTP {method} {path} - {status} {errorMessage} - IP: {clientIP}"
        probability: 0.2
        metadata:
          component: api-gateway
  
  application:
    enabled: true
    frequency: 60000   # 1,000 logs/second
    templates:
      - level: INFO
        messageTemplate: User {userId} performed action {action} on resource {resourceId}
        probability: 0.7
        metadata:
          component: business-logic
      - level: ERROR
        messageTemplate: "Database connection failed: {errorMessage}"
        probability: 0.3
        metadata:
          component: database
  
  server:
    enabled: true
    frequency: 60000   # 1,000 logs/second
    templates:
      - level: INFO
        messageTemplate: "System load: {loadAverage} - CPU: {cpuUsage}% Memory: {memoryUsage}%"
        probability: 0.6
        metadata:
          component: system-monitor
      - level: WARN
        messageTemplate: "High CPU usage detected: {cpuUsage}% for {duration}s"
        probability: 0.4
        metadata:
          component: performance-monitor
  
  firewall:
    enabled: true
    frequency: 60000   # 1,000 logs/second
    templates:
      - level: INFO
        messageTemplate: "ACCEPT {protocol} {srcIP}:{srcPort} -> {dstIP}:{dstPort}"
        probability: 0.9
        metadata:
          component: packet-filter
      - level: WARN
        messageTemplate: "DROP {protocol} {srcIP}:{srcPort} -> {dstIP}:{dstPort}"
        probability: 0.1
        metadata:
          component: packet-filter

  # Disable lower-priority generators to focus on high-volume sources
  cloud:
    enabled: false
  authentication:
    enabled: false
  database:
    enabled: false
  webserver:
    enabled: false
  email:
    enabled: false
  backup:
    enabled: false
  microservices:
    enabled: false
  iot:
    enabled: false

replay:
  enabled: false
  speed: 1
  loop: false

output:
  format: json
  destination: file
  batching:
    maxBatchSize: 1000      # Larger batches for better performance
    flushIntervalMs: 100    # Faster flushing
    enabled: true
  file:
    path: ./logs/current/logs.json
    rotation: true
    maxSize: 500MB          # Larger files before rotation
    maxFiles: 20

storage:
  historicalPath: ./logs/historical
  currentPath: ./logs/current
  retention: 7              # Shorter retention for performance testing
